import { IconConstant } from '../shared/constants/icon-constants/icon-constant';
export interface Appointment {
  id?: string;
  title?: string;
  status?: 'completed' | 'cancelled' | 'completed';
  statusText?: string;
  branch?: string;
  date: string;
  time?: string;
  personalNumber?: string;
  selected?: boolean;
  phone?: number;
  email?: string;
  nationality?: string;
  passportNumber?: string;
  appointmentNumber?: number;
  notAttended?: number;
  cancelledAppointment?: number;
  recentAppointmentDate?: string;
  recentAppointmentTime?: string;
  successfulAppointments?: number;
  lastAppointmentBooked?: string;
  lastAppointmentTime?: string;
  day?: string;
  agentCR?: string;
  agentNumber2?: string;
  cpr?: string[];
  declinedCpr?: string[];
}

export interface card {
  id?: number;
  title?: string;
  info?:
    | string
    | string[]
    | { title: string; description: string }[]
    | number
    | any;
  icon?: string | any;
  sub?: string;
  style?: string;
  styleInfo?: string;
  stylesub?: string;
  iconColor?: string;
}

export interface OverallDashboardCard {
  id: number;
  cardIcon: string | any;
  cardTitle: string;
  cardValue: string;
  cardTrend?: string | null;
  trendType?: 'positive' | 'negative' | 'warning' | '' | null;
}

export interface USERS_INFO_DASHBOARD {
  id: number;
  cardIcon: string | any;
  cardTitle: string;
  cardValue: any;
  cardTrend: string;
  trendType: string;
}

export interface blockedperson {
  cpr: string;
  appointmentDate: string | null;
  appointmentTime: string | null;
  isBlocked: Boolean;
  unblockDate: string | any;
  blockReason: string;
}

export interface periods {
  day?: string;
  date1?: string;
  date2?: string;
  availableAppointments?: number;
  bookedAppointments?: number;
  totalAppointments?: number;
}

export interface AppointmentBranchFlat {
  branchName: string;
  day: string;
  date1: string;
  date2: string;
  availableAppointments: number;
  bookedAppointments: number;
  totalAppointments: number;
  periods: Array<{
    availableAppointments2: number;
    bookedAppointments2: number;
    remainingAppointments: number;
    periods: string;
  }>;
}

export interface appoitmentTableNormal {
  cpr: string;
  appointmentDate: string;
  time: string;
  place: string;
}

export interface StatisticsData {
  startDate: Date;
  endDate: Date;
  reports: {
    metric: string;
    isaTown: string | number;
    muharraq: string | number;
  }[];
}
export interface NotificationTable {
  icon?: string | any;
  notificationType?: string;
  date?: string;
  time?: string;
  description?: string;
  date_count?: string;
  user?: string;
  cpr?: string;
  priority?: 'high' | 'medium' | 'low' | '' | null;
}

export interface CalendarDate {
  date: string;
  dayName?: string;
  dayNumber?: number;
  monthNumber?: number;
  monthName?: string;
  year?: number;
  totalAppointment?: number;
  bookedAppointment?: number;
  unbookedAppointment?: number;
  startTime?: string;
  endTime?: string;
  period?: string;
  branch?: string;
  backgroundColor?: string;
}

export class data {
  static readonly HEADER_TITLE = 'نظام إدارة المواعيد';
  static readonly HEADER_APPOINTMENT_TITLE = 'إدارة  مواعيد العملاء';
  static readonly HEADER_APPOINTMENT_DESCRIPTION =
    'إدارة  ومراقبة جميع مواعيد العملاء';
  static readonly ANALYSIS_HEADER = '  التقارير الإحصائية للفروع';
  static readonly ANALYSIS_DESCRIPTION = 'مقارنة أداء الفروع';
  static readonly NOTIFICATION_HEADER = 'الاشعارات';
  static readonly ADD_BRANCH_FORM_TITLE = ' إضافة فرع ';
  static readonly ADD_BRANCH_FORM_BRANCH_NAME_PLACEHOLDER =
    ' ادخل اسم الفرع المراد اضافته';

  static readonly WORKING_HOURS = [
    '08:00',
    '08:30',
    '09:00',
    '09:30',
    '10:00',
    '10:30',
    '11:00',
    '11:30',
    '12:00',
    '12:30',
    '13:00',
    '13:30',
    '14:00',
    '14:30',
    '15:00',
    '15:30',
    '16:00',
  ];

  static readonly period = [
    {
      label: ' يوميًا ',
      value: 1,
    },
    {
      label: ' اسبوعيًا ',
      value: 7,
    },
    {
      label: ' شهريًا ',
      value: 30,
    },
  ];

  static readonly NON_BAHRAINI_BRANCHS = [2, 5, 3];

  static readonly OVERALL_DASHBOARD: card[] = [
    {
      id: 1,
      icon: IconConstant.TICKET,
      title: 'المواعيد اليوم',
      info: '24',
      sub: '+2% من أمس',
    },
    {
      id: 2,
      icon: IconConstant.TIME,
      title: 'المواعيد المتاخرة',
      info: '13',
      sub: '-15% من أمس',
    },
    {
      id: 3,
      icon: IconConstant.USERS,
      title: 'إجمالي الحضور',
      info: '523',
      sub: '+5% من أمس',
    },
    {
      id: 4,
      icon: IconConstant.CALENDAR,
      title: 'المواعيد اليوم',
      info: '125',
      sub: '+25% من أمس',
    },
  ] as const;
  static readonly BRANCH_STATUS = [
    {
      id: 1,
      branchName: 'مدينة عيسى',
      cancledAttendancesCount: 3,
      attendanceCount: 43,
      appointmentsCount: 75,
      waitTime: '14',
      status: 'فعال',
      statusDescription: '',
    },
    {
      id: 2,
      branchName: 'المحرق',
      cancledAttendancesCount: 12,
      attendanceCount: 31,
      appointmentsCount: 35,
      waitTime: '8',
      status: 'فعال',
      statusDescription: '',
    },
    {
      id: 3,
      branchName: 'ميناء سلمان',
      status: 'غير فعال',
      cancledAttendancesCount: 0,
      attendanceCount: 0,
      appointmentsCount: 0,
      waitTime: '0',
      statusDescription: 'لا يوجد اتصال بالإنترنت',
    },
    {
      id: 4,
      branchName: 'مدينة عيسى - اصدار بطاقة هوية',
      status: ' فعال',
      cancledAttendancesCount: 0,
      attendanceCount: 0,
      appointmentsCount: 0,
      waitTime: '0',
      statusDescription: ' ',
    },
    {
      id: 5,
      branchName: 'مدينة عيسى - تجديد بطاقة الهوية',
      status: 'غير فعال',
      cancledAttendancesCount: 0,
      attendanceCount: 0,
      appointmentsCount: 0,
      waitTime: '0',
      statusDescription: 'لا يوجد اتصال بالإنترنت',
    },
  ];
  static readonly PEAK_TIMES = [
    {
      id: 1,
      cardIcon: IconConstant.CLOCK,
      cardTitle: 'أكثر ساعة ازدحام',
      cardValue: '10AM',
      cardTrend: '',
      trendType: '' as const,
    },
    {
      id: 2,
      cardIcon: IconConstant.WAVE,
      cardTitle: 'معدل الازدحام',
      cardValue: '40% ',
      cardTrend: '',
      trendType: '' as const,
    },
    {
      id: 3,
      cardIcon: IconConstant.CLOCK2,
      cardTitle: 'الحدلى الأقصى للانتظار',
      cardValue: '37 دقيقة',
      cardTrend: '+5% من أمس',
      trendType: 'positive' as const,
    },
    {
      id: 4,
      cardIcon: IconConstant.TASK,
      cardTitle: 'أكثر يوم ازدحام خلال الاسبوع',
      cardValue: 'الأحد',
      cardTrend: '',
      trendType: '' as const,
    },
  ] as const;

  static readonly BRANCH_PEAK_TIMES: {
    [branchId: string]: OverallDashboardCard[];
  } = {
    '1': [
      // مدينة عيسى
      {
        id: 1,
        cardIcon: IconConstant.CLOCK,
        cardTitle: 'أكثر ساعة ازدحام',
        cardValue: '10AM',
        cardTrend: null,
        trendType: '',
      },
      {
        id: 2,
        cardIcon: IconConstant.WAVE,
        cardTitle: 'معدل الازدحام',
        cardValue: '65%',
        cardTrend: '+12% من أمس',
        trendType: 'positive',
      },
      {
        id: 3,
        cardIcon: IconConstant.CLOCK2,
        cardTitle: 'الحد الأقصى للانتظار',
        cardValue: '14 دقيقة',
        cardTrend: '-8% من أمس',
        trendType: 'negative',
      },
      {
        id: 4,
        cardIcon: IconConstant.TASK,
        cardTitle: 'أكثر يوم ازدحام خلال الاسبوع',
        cardValue: 'الثلاثاء',
        cardTrend: null,
        trendType: '',
      },
    ],
    '2': [
      // المحرق
      {
        id: 1,
        cardIcon: IconConstant.CLOCK,
        cardTitle: 'أكثر ساعة ازدحام',
        cardValue: '11AM',
        cardTrend: null,
        trendType: '',
      },
      {
        id: 2,
        cardIcon: IconConstant.WAVE,
        cardTitle: 'معدل الازدحام',
        cardValue: '45%',
        cardTrend: '-3% من أمس',
        trendType: 'negative',
      },
      {
        id: 3,
        cardIcon: IconConstant.CLOCK2,
        cardTitle: 'الحد الأقصى للانتظار',
        cardValue: '8 دقائق',
        cardTrend: '-15% من أمس',
        trendType: 'negative',
      },
      {
        id: 4,
        cardIcon: IconConstant.TASK,
        cardTitle: 'أكثر يوم ازدحام خلال الاسبوع',
        cardValue: 'الأحد',
        cardTrend: null,
        trendType: '',
      },
    ],
    '3': [
      // ميناء سلمان
      {
        id: 1,
        cardIcon: IconConstant.CLOCK,
        cardTitle: 'أكثر ساعة ازدحام',
        cardValue: 'غير متاح',
        cardTrend: null,
        trendType: '',
      },
      {
        id: 2,
        cardIcon: IconConstant.WAVE,
        cardTitle: 'معدل الازدحام',
        cardValue: '0%',
        cardTrend: 'غير نشط',
        trendType: 'warning',
      },
      {
        id: 3,
        cardIcon: IconConstant.CLOCK2,
        cardTitle: 'الحد الأقصى للانتظار',
        cardValue: '0 دقيقة',
        cardTrend: 'غير نشط',
        trendType: 'warning',
      },
      {
        id: 4,
        cardIcon: IconConstant.TASK,
        cardTitle: 'أكثر يوم ازدحام خلال الاسبوع',
        cardValue: 'غير متاح',
        cardTrend: null,
        trendType: '',
      },
    ],
    '4': [
      // مدينة عيسى - اصدار بطاقة هوية
      {
        id: 1,
        cardIcon: IconConstant.CLOCK,
        cardTitle: 'أكثر ساعة ازدحام',
        cardValue: '11AM',
        cardTrend: null,
        trendType: '',
      },
      {
        id: 2,
        cardIcon: IconConstant.WAVE,
        cardTitle: 'معدل الازدحام',
        cardValue: '55%',
        cardTrend: '+8% من أمس',
        trendType: 'positive',
      },
      {
        id: 3,
        cardIcon: IconConstant.CLOCK2,
        cardTitle: 'الحد الأقصى للانتظار',
        cardValue: '52 دقيقة',
        cardTrend: '+3% من أمس',
        trendType: 'positive',
      },
      {
        id: 4,
        cardIcon: IconConstant.TASK,
        cardTitle: 'أكثر يوم ازدحام خلال الاسبوع',
        cardValue: 'الاثنين',
        cardTrend: null,
        trendType: '',
      },
    ],
    '5': [
      // مدينة عيسى - تجديد بطاقة الهوية
      {
        id: 1,
        cardIcon: IconConstant.CLOCK,
        cardTitle: 'أكثر ساعة ازدحام',
        cardValue: 'غير متاح',
        cardTrend: null,
        trendType: '',
      },
      {
        id: 2,
        cardIcon: IconConstant.WAVE,
        cardTitle: 'معدل الازدحام',
        cardValue: '5%',
        cardTrend: 'غير نشط',
        trendType: 'warning',
      },
      {
        id: 3,
        cardIcon: IconConstant.CLOCK2,
        cardTitle: 'الحد الأقصى للانتظار',
        cardValue: '3 دقائق',
        cardTrend: 'غير نشط',
        trendType: 'warning',
      },
      {
        id: 4,
        cardIcon: IconConstant.TASK,
        cardTitle: 'أكثر يوم ازدحام خلال الاسبوع',
        cardValue: 'غير متاح',
        cardTrend: null,
        trendType: '',
      },
    ],
  };

  // Chart data interface for dual line chart
  static readonly BRANCH_CHART_DATA: {
    [branchId: string]: { waitTimes: number[]; appointments: number[] };
  } = {
    // Default/Average data (when no branch is selected)
    default: {
      waitTimes: [13, 17, 31, 47, 60, 79, 58, 43, 27, 18, 15, 10],
      appointments: [15, 19, 40, 55, 86, 47, 50, 70, 40, 30, 20, 15],
    },
    // Branch 1: مدينة عيسى
    '1': {
      waitTimes: [8, 12, 25, 42, 65, 85, 72, 55, 38, 22, 16, 11],
      appointments: [20, 25, 45, 60, 95, 75, 68, 82, 52, 38, 28, 18],
    },
    // Branch 2: المحرق
    '2': {
      waitTimes: [5, 8, 15, 28, 35, 45, 38, 25, 18, 12, 8, 6],
      appointments: [12, 16, 28, 42, 55, 35, 40, 58, 35, 25, 18, 12],
    },
    // Branch 3: ميناء سلمان (inactive branch - low numbers)
    '3': {
      waitTimes: [0, 0, 2, 3, 5, 3, 2, 1, 0, 0, 0, 0],
      appointments: [0, 0, 5, 8, 12, 8, 5, 3, 0, 0, 0, 0],
    },
    // Branch 4: مدينة عيسى - اصدار بطاقة هوية
    '4': {
      waitTimes: [10, 15, 22, 35, 45, 52, 48, 35, 25, 18, 12, 8],
      appointments: [8, 12, 18, 25, 32, 28, 25, 30, 22, 15, 10, 6],
    },
    // Branch 5: مدينة عيسى - تجديد بطاقة الهوية (inactive)
    '5': {
      waitTimes: [0, 0, 1, 2, 3, 2, 1, 1, 0, 0, 0, 0],
      appointments: [0, 0, 2, 4, 6, 4, 3, 2, 0, 0, 0, 0],
    },
  };

  static readonly APPOINTMENTS_LIST: Appointment[] = [
    {
      id: '1',
      title: 'إصدار بطاقة الهوية',
      status: 'completed',
      statusText: 'مكتمل',
      branch: 'مدينة عيسى',
      date: '2025-09-21',
      time: '10:00',
      personalNumber: '920101234',
      selected: false,
      phone: 12345678,
      email: 'agent.mohammed@agency.com',
      nationality: 'بحريني',
      passportNumber: 'AG1234567',
      appointmentNumber: 101,
      notAttended: 1,
      cancelledAppointment: 5,
      recentAppointmentDate: '2025-09-01',
      recentAppointmentTime: '09:30',
      successfulAppointments: 5,
      lastAppointmentBooked: '2025-08-15',
      lastAppointmentTime: '11:00',
      day: 'الاحد',
      agentCR: 'CR998877',
      agentNumber2: '55001122',
      cpr: ['920101234', '920101235'],
      declinedCpr: ['920101239'],
    },
    {
      id: '2',
      title: 'تجديد بطاقة الهوية',
      status: 'completed',
      statusText: 'مكتمل',
      branch: 'المحرق',
      date: '2025-09-15',
      time: '14:00',
      personalNumber: '02093185',
      selected: false,
      phone: 98765432,
      email: 'fatima.hasan@example.com',
      nationality: 'بحرينية',
      passportNumber: 'BH123456',
      appointmentNumber: 102,
      cancelledAppointment: 15,
      notAttended: 0,
      recentAppointmentDate: '2025-08-25',
      recentAppointmentTime: '10:00',
      successfulAppointments: 3,
      lastAppointmentBooked: '2025-08-01',
      lastAppointmentTime: '09:00',
      day: 'الاثنين',
      agentCR: undefined,
      agentNumber2: undefined,
      cpr: undefined,
      declinedCpr: undefined,
    },
    {
      id: '3',
      status: 'cancelled',
      statusText: 'ملغي',
      branch: 'مدينة عيسى',
      date: '2025-09-10',
      time: '12:30',
      personalNumber: '930202345',
      selected: false,
      phone: 87654321,
      email: 'fatima.agent@servicehub.com',
      nationality: 'بحرينية',
      passportNumber: 'AG7654321',
      appointmentNumber: 103,
      notAttended: 2,
      cancelledAppointment: 34,
      recentAppointmentDate: '2025-08-18',
      recentAppointmentTime: '08:45',
      successfulAppointments: 8,
      lastAppointmentBooked: '2025-08-10',
      lastAppointmentTime: '13:00',
      day: 'الثلاثاء',
      agentCR: 'CR887766',
      agentNumber2: '55990077',
      cpr: ['930202345', '930202346'],
      declinedCpr: ['930202349'],
    },
    {
      id: '4',
      status: 'completed',
      statusText: 'مكتمل',
      branch: 'مدينة عيسى',
      date: '2025-09-18',
      time: '11:00',
      personalNumber: '73812356',
      selected: false,
      phone: 99887766,
      email: 'yousef.saeed88@testmail.com',
      nationality: 'بحريني',
      passportNumber: 'BH34632',
      appointmentNumber: 104,
      notAttended: 3,
      cancelledAppointment: 33,
      recentAppointmentDate: '2025-09-05',
      recentAppointmentTime: '09:45',
      successfulAppointments: 12,
      lastAppointmentBooked: '2025-08-28',
      lastAppointmentTime: '10:15',
      day: 'الاربعاء',
      agentCR: undefined,
      agentNumber2: undefined,
      cpr: undefined,
      declinedCpr: undefined,
    },
    {
      id: '5',
      status: 'completed',
      statusText: 'مكتمل',
      branch: 'المحرق',
      date: '2025-09-20',
      time: '13:00',
      personalNumber: '940303456',
      selected: false,
      phone: 55443322,
      email: 'yousef.agent@helpdesk.net',
      nationality: 'بحريني',
      passportNumber: 'AG1112223',
      appointmentNumber: 105,
      notAttended: 1,
      cancelledAppointment: 15,
      recentAppointmentDate: '2025-09-12',
      recentAppointmentTime: '08:30',
      successfulAppointments: 10,
      lastAppointmentBooked: '2025-08-30',
      lastAppointmentTime: '09:45',
      day: 'الخميس',
      agentCR: 'CR776655',
      agentNumber2: '55443322',
      cpr: ['940303456', '940303457'],
      declinedCpr: ['940303459'],
    },
    {
      id: '6',
      status: 'completed',
      statusText: 'مكتمل',
      branch: 'مدينة عيسى',
      date: '2025-09-17',
      time: '15:30',
      personalNumber: '020912226',
      selected: false,
      phone: 66554433,
      email: 'ali.khalifa91@example.com',
      nationality: 'بحريني',
      passportNumber: 'BH45678',
      appointmentNumber: 106,
      cancelledAppointment: 35,
      notAttended: 0,
      recentAppointmentDate: '2025-09-05',
      recentAppointmentTime: '11:00',
      successfulAppointments: 7,
      lastAppointmentBooked: '2025-08-20',
      lastAppointmentTime: '13:30',
      day: 'الاحد',
      agentCR: undefined,
      agentNumber2: undefined,
      cpr: undefined,
      declinedCpr: undefined,
    },
    {
      id: '7',
      status: 'completed',
      statusText: 'مكتمل',
      branch: 'مدينة عيسى',
      date: '2025-09-22',
      time: '09:00',
      personalNumber: '950404567',
      selected: false,
      phone: 55112233,
      email: 'layla.agent@supportcenter.org',
      nationality: 'بحرينية',
      passportNumber: 'AG2223334',
      appointmentNumber: 107,
      cancelledAppointment: 22,
      notAttended: 0,
      recentAppointmentDate: '2025-09-10',
      recentAppointmentTime: '10:30',
      successfulAppointments: 15,
      lastAppointmentBooked: '2025-08-25',
      lastAppointmentTime: '14:00',
      day: 'الاثنين',
      agentCR: 'CR665544',
      agentNumber2: '55112233',
      cpr: ['950404567', '950404568'],
      declinedCpr: ['950404569'],
    },
    {
      id: '8',
      status: 'cancelled',
      statusText: 'ملغي',
      branch: 'المحرق',
      date: '2025-09-23',
      time: '10:30',
      personalNumber: '020998877',
      selected: false,
      phone: 44556677,
      email: 'noor.jassim@demo.org',
      nationality: 'بحرينية',
      passportNumber: 'BH998877',
      appointmentNumber: 108,
      cancelledAppointment: 15,
      notAttended: 2,
      recentAppointmentDate: '2025-09-18',
      recentAppointmentTime: '11:30',
      successfulAppointments: 4,
      lastAppointmentBooked: '2025-08-28',
      lastAppointmentTime: '13:00',
      day: 'الثلاثاء',
      agentCR: undefined,
      agentNumber2: undefined,
      cpr: undefined,
      declinedCpr: undefined,
    },
    {
      id: '9',
      status: 'completed',
      statusText: 'مكتمل',
      branch: 'المحرق',
      date: '2025-09-14',
      time: '11:15',
      personalNumber: '960505678',
      selected: false,
      phone: 55334411,
      email: 'dana.rashed@agentline.com',
      nationality: 'بحرينية',
      passportNumber: 'AG3334445',
      appointmentNumber: 109,
      cancelledAppointment: 15,
      notAttended: 1,
      recentAppointmentDate: '2025-09-05',
      recentAppointmentTime: '12:30',
      successfulAppointments: 20,
      lastAppointmentBooked: '2025-09-01',
      lastAppointmentTime: '10:00',
      day: 'الاربعاء',
      agentCR: 'CR554433',
      agentNumber2: '55334411',
      cpr: ['960505678', '960505679'],
      declinedCpr: ['960505680'],
    },
  ];

  static readonly TIME_PERIOD = [
    {
      id: 1,
      date: '2023-10-01',
      time: '10:00',
      period: 'صباحاً',
      day: 'الأحد',
    },
  ];

  static readonly Blocked: blockedperson[] = [
    {
      cpr: '981234567',
      appointmentDate: '2025-09-30',
      appointmentTime: '14:30',
      isBlocked: true,
      unblockDate: '2025-10-05',
      blockReason: 'لم يحضر الموعد السابق',
    },
    {
      cpr: '920187543',
      appointmentDate: '2025-10-02',
      appointmentTime: '09:00',
      isBlocked: false,
      unblockDate: null,
      blockReason: '',
    },
    {
      cpr: '890234112',
      appointmentDate: '2025-10-10',
      appointmentTime: '11:15',
      isBlocked: true,
      unblockDate: '2025-10-20',
      blockReason: 'حظر مؤقت بسبب عدم إحضار المستندات',
    },
    {
      cpr: '950334112',
      appointmentDate: '2025-09-28',
      appointmentTime: '08:45',
      isBlocked: false,
      unblockDate: null,
      blockReason: '',
    },
    {
      cpr: '901112233',
      appointmentDate: '2025-09-26',
      appointmentTime: '13:00',
      isBlocked: true,
      unblockDate: '2025-10-01',
      blockReason: 'إلغاء الموعد في آخر لحظة',
    },
    {
      cpr: '881122334',
      appointmentDate: '2025-10-01',
      appointmentTime: '16:00',
      isBlocked: false,
      unblockDate: null,
      blockReason: '',
    },
    {
      cpr: '991133445',
      appointmentDate: '2025-10-03',
      appointmentTime: '10:30',
      isBlocked: true,
      unblockDate: '2025-10-08',
      blockReason: 'تم الحظر بعد التأخير لأكثر من مرة',
    },
    {
      cpr: '951122667',
      appointmentDate: '2025-10-04',
      appointmentTime: '12:00',
      isBlocked: false,
      unblockDate: null,
      blockReason: '',
    },
    {
      cpr: '961245789',
      appointmentDate: '2025-10-05',
      appointmentTime: '15:00',
      isBlocked: true,
      unblockDate: '2025-10-12',
      blockReason: 'محاولة الدخول بدون موعد',
    },
    {
      cpr: '991998877',
      appointmentDate: null,
      appointmentTime: null,
      isBlocked: false,
      unblockDate: null,
      blockReason: '',
    },
  ];
  //Filter options for peak times component
  static readonly PEAK_DATA_BY_BRANCH = {
    MAADI_ISA: {
      branchName: 'MAADI_ISA',
      cards: [
        {
          id: 1,
          cardIcon: IconConstant.CLOCK,
          cardTitle: 'أكثر ساعة ازدحام',
          cardValue: '11AM',
          cardTrend: null,
          trendType: null,
        },
        {
          id: 2,
          cardIcon: IconConstant.WAVE,
          cardTitle: 'معدل الازدحام',
          cardValue: '55%',
          cardTrend: '+3% من أمس',
          trendType: 'positive' as const,
        },
        {
          id: 3,
          cardIcon: IconConstant.CLOCK2,
          cardTitle: 'الحدلى الأقصى للانتظار',
          cardValue: '28 دقيقة',
          cardTrend: '-2% من أمس',
          trendType: 'negative' as const,
        },
        {
          id: 4,
          cardIcon: IconConstant.TASK,
          cardTitle: 'أكثر يوم ازدحام خلال الاسبوع',
          cardValue: 'الإثنين',
          cardTrend: null,
          trendType: null,
        },
      ],
      chart: {
        labels: [
          '6AM',
          '7AM',
          '8AM',
          '9AM',
          '10AM',
          '11AM',
          '12PM',
          '1PM',
          '2PM',
          '3PM',
          '4PM',
          '5PM',
        ],
        datasets: [
          {
            data: [10, 15, 28, 35, 45, 52, 40, 30, 20, 15, 10, 8],
            label: 'وقت الانتظار (دقيقة)',
            borderColor: 'rgba(239,72,72,1)',
            backgroundColor: 'rgba(239,72,72,0.4)',
            yAxisID: 'y-axis-0',
          },
          {
            data: [12, 18, 30, 48, 58, 65, 60, 50, 35, 25, 20, 18],
            label: 'عدد المواعيد',
            borderColor: 'rgba(29,37,55,1)',
            backgroundColor: 'rgba(29,37,55,0.4)',
            yAxisID: 'y-axis-1',
          },
        ],
      },
    },
    MINA_SALMAN: {
      branchName: 'MINA_SALMAN',
      cards: [
        {
          id: 1,
          cardIcon: IconConstant.CLOCK,
          cardTitle: 'أكثر ساعة ازدحام',
          cardValue: '1PM',
          cardTrend: null,
          trendType: null,
        },
        {
          id: 2,
          cardIcon: IconConstant.WAVE,
          cardTitle: 'معدل الازدحام',
          cardValue: '70%',
          cardTrend: '+8% من أمس',
          trendType: 'positive' as const,
        },
        {
          id: 3,
          cardIcon: IconConstant.CLOCK2,
          cardTitle: 'الحدلى الأقصى للانتظار',
          cardValue: '42 دقيقة',
          cardTrend: '+10% من أمس',
          trendType: 'positive' as const,
        },
        {
          id: 4,
          cardIcon: IconConstant.TASK,
          cardTitle: 'أكثر يوم ازدحام خلال الاسبوع',
          cardValue: 'الأربعاء',
          cardTrend: null,
          trendType: null,
        },
      ],
      chart: {
        labels: [
          '6AM',
          '7AM',
          '8AM',
          '9AM',
          '10AM',
          '11AM',
          '12PM',
          '1PM',
          '2PM',
          '3PM',
          '4PM',
          '5PM',
        ],
        datasets: [
          {
            data: [12, 18, 25, 38, 50, 60, 70, 75, 60, 45, 30, 20],
            label: 'وقت الانتظار (دقيقة)',
            borderColor: 'rgba(239,72,72,1)',
            backgroundColor: 'rgba(239,72,72,0.4)',
            yAxisID: 'y-axis-0',
          },
          {
            data: [14, 20, 30, 50, 70, 85, 90, 95, 80, 60, 40, 30],
            label: 'عدد المواعيد',
            borderColor: 'rgba(29,37,55,1)',
            backgroundColor: 'rgba(29,37,55,0.4)',
            yAxisID: 'y-axis-1',
          },
        ],
      },
    },
    MUHARRAQ: {
      branchName: 'MUHARRAQ',
      cards: [
        {
          id: 1,
          cardIcon: IconConstant.CLOCK,
          cardTitle: 'أكثر ساعة ازدحام',
          cardValue: '9AM',
          cardTrend: null,
          trendType: null,
        },
        {
          id: 2,
          cardIcon: IconConstant.WAVE,
          cardTitle: 'معدل الازدحام',
          cardValue: '35%',
          cardTrend: '-5% من أمس',
          trendType: 'negative' as const,
        },
        {
          id: 3,
          cardIcon: IconConstant.CLOCK2,
          cardTitle: 'الحد الأقصى للانتظار',
          cardValue: '20 دقيقة',
          cardTrend: '-7% من أمس',
          trendType: 'negative' as const,
        },
        {
          id: 4,
          cardIcon: IconConstant.TASK,
          cardTitle: 'أكثر يوم ازدحام خلال الاسبوع',
          cardValue: 'الخميس',
          cardTrend: null,
          trendType: null,
        },
      ],
      chart: {
        labels: [
          '6AM',
          '7AM',
          '8AM',
          '9AM',
          '10AM',
          '11AM',
          '12PM',
          '1PM',
          '2PM',
          '3PM',
          '4PM',
          '5PM',
        ],
        datasets: [
          {
            data: [5, 8, 15, 20, 18, 16, 14, 12, 10, 8, 6, 5],
            label: 'وقت الانتظار (دقيقة)',
            borderColor: 'rgba(239,72,72,1)',
            backgroundColor: 'rgba(239,72,72,0.4)',
            yAxisID: 'y-axis-0',
          },
          {
            data: [10, 12, 18, 22, 20, 18, 15, 13, 11, 9, 8, 7],
            label: 'عدد المواعيد',
            borderColor: 'rgba(29,37,55,1)',
            backgroundColor: 'rgba(29,37,55,0.4)',
            yAxisID: 'y-axis-1',
          },
        ],
      },
    },
    ID_ISSUE: {
      branchName: 'ID_ISSUE',
      cards: [
        {
          id: 1,
          cardIcon: IconConstant.CLOCK,
          cardTitle: 'أكثر ساعة ازدحام',
          cardValue: '12PM',
          cardTrend: null,
          trendType: null,
        },
        {
          id: 2,
          cardIcon: IconConstant.WAVE,
          cardTitle: 'معدل الازدحام',
          cardValue: '60%',
          cardTrend: '+4% من أمس',
          trendType: 'positive' as const,
        },
        {
          id: 3,
          cardIcon: IconConstant.CLOCK2,
          cardTitle: 'الحدلى الأقصى للانتظار',
          cardValue: '33 دقيقة',
          cardTrend: '+2% من أمس',
          trendType: 'positive' as const,
        },
        {
          id: 4,
          cardIcon: IconConstant.TASK,
          cardTitle: 'أكثر يوم ازدحام خلال الاسبوع',
          cardValue: 'الثلاثاء',
          cardTrend: null,
          trendType: null,
        },
      ],
      chart: {
        labels: [
          '6AM',
          '7AM',
          '8AM',
          '9AM',
          '10AM',
          '11AM',
          '12PM',
          '1PM',
          '2PM',
          '3PM',
          '4PM',
          '5PM',
        ],
        datasets: [
          {
            data: [8, 10, 20, 30, 45, 50, 55, 48, 36, 28, 20, 15],
            label: 'وقت الانتظار (دقيقة)',
            borderColor: 'rgba(239,72,72,1)',
            backgroundColor: 'rgba(239,72,72,0.4)',
            yAxisID: 'y-axis-0',
          },
          {
            data: [10, 15, 25, 40, 60, 70, 80, 65, 50, 35, 25, 20],
            label: 'عدد المواعيد',
            borderColor: 'rgba(29,37,55,1)',
            backgroundColor: 'rgba(29,37,55,0.4)',
            yAxisID: 'y-axis-1',
          },
        ],
      },
    },
    ID_RENEWAL: {
      branchName: 'ID_RENEWAL',
      cards: [
        {
          id: 1,
          cardIcon: IconConstant.CLOCK,
          cardTitle: 'أكثر ساعة ازدحام',
          cardValue: '2PM',
          cardTrend: null,
          trendType: null,
        },
        {
          id: 2,
          cardIcon: IconConstant.WAVE,
          cardTitle: 'معدل الازدحام',
          cardValue: '45%',
          cardTrend: '-3% من أمس',
          trendType: 'negative' as const,
        },
        {
          id: 3,
          cardIcon: IconConstant.CLOCK2,
          cardTitle: 'الحدلى الأقصى للانتظار',
          cardValue: '25 دقيقة',
          cardTrend: '-1% من أمس',
          trendType: 'negative' as const,
        },
        {
          id: 4,
          cardIcon: IconConstant.TASK,
          cardTitle: 'أكثر يوم ازدحام خلال الاسبوع',
          cardValue: 'الأحد',
          cardTrend: null,
          trendType: null,
        },
      ],
      chart: {
        labels: [
          '6AM',
          '7AM',
          '8AM',
          '9AM',
          '10AM',
          '11AM',
          '12PM',
          '1PM',
          '2PM',
          '3PM',
          '4PM',
          '5PM',
        ],
        datasets: [
          {
            data: [7, 9, 18, 25, 32, 35, 40, 42, 45, 40, 30, 25],
            label: 'وقت الانتظار (دقيقة)',
            borderColor: 'rgba(239,72,72,1)',
            backgroundColor: 'rgba(239,72,72,0.4)',
            yAxisID: 'y-axis-0',
          },
          {
            data: [10, 14, 20, 28, 36, 45, 55, 60, 58, 50, 40, 30],
            label: 'عدد المواعيد',
            borderColor: 'rgba(29,37,55,1)',
            backgroundColor: 'rgba(29,37,55,0.4)',
            yAxisID: 'y-axis-1',
          },
        ],
      },
    },
  };

  static readonly USERSINFO: USERS_INFO_DASHBOARD[] = [
    {
      id: 1,
      cardIcon: IconConstant.TICKET,
      cardTitle: 'اليوم',
      cardValue: new Date(),
      cardTrend: '+2% من أمس',
      trendType: 'positive' as const,
    },
    {
      id: 2,
      cardIcon: IconConstant.TIME,
      cardTitle: 'المواعيد المتاخرة',
      cardValue: '13',
      cardTrend: '-15% من أمس',
      trendType: 'negative' as const,
    },
    {
      id: 3,
      cardIcon: IconConstant.USERS,
      cardTitle: 'إجمالي الحضور',
      cardValue: '523',
      cardTrend: '+5% من أمس',
      trendType: 'warning' as const,
    },
    {
      id: 4,
      cardIcon: IconConstant.CALENDAR,
      cardTitle: 'المواعيد اليوم',
      cardValue: '125',
      cardTrend: '+25% من أمس',
      trendType: 'positive' as const,
    },
  ] as const;

  static readonly cardItems: card[] = [
    {
      id: 1,
      title: '  اليوم ',
      icon: IconConstant.CALENDAR,
      info: new Date(),
    },
    {
      id: 2,
      title: ' اجمالي مستخدمين النظام ',
      icon: IconConstant.USERS,

      info: '4',
      styleInfo: 'background-color: pink;',
    },
    {
      id: 3,
      title: ' النشاط الاخير ',
      icon: IconConstant.TIME,
      info: [
        { title: '  احمد حسين  ', description: '01-09-2025' },
        { title: ' مريم علي ', description: '01-09-2025' },
      ],
    },
    {
      id: 4,
      title: 'حالة المستخدمين',
      icon: IconConstant.TICKET,
      info: [
        { title: 'فعال', description: '3' },
        { title: 'غير مفعل', description: '1' },
      ],
    },
  ];

  static readonly analysisCard: card[] = [
    {
      id: 1,
      title: '  المواعيد  ',
      icon: IconConstant.CALENDAR,
      info: '630',
      sub: '  25+ % من الفترة السابقة  ',
    },
    {
      id: 2,
      title: ' إجمالي الحضور   ',
      icon: IconConstant.USERS,
      info: '530',
      sub: '  25+ % من الفترة السابقة   ',
    },
    {
      id: 3,
      title: ' النشاط الاخير ',
      icon: IconConstant.TIME,
      info: ' 13 دقيقة ',
      sub: '  -15٪ من الفترة السابقة ',
    },
    {
      id: 4,
      title: 'حالة المواعيد الملغية',
      icon: IconConstant.TICKET,
      info: '46',
    },
  ];

  static readonly analysisTicketCard: card[] = [
    {
      id: 1,
      title: '  إجمالي التذاكر  ',
      icon: IconConstant.TICKET,
      info: '630',
      iconColor: 'orange',
    },
    {
      id: 2,
      title: '  التذاكر المطبوعة   ',
      icon: IconConstant.TICKET,
      info: '530',
      iconColor: 'green',
    },
    {
      id: 3,
      title: '  التذاكر غير المطبوعة ',
      icon: IconConstant.TICKET,
      info: ' 13 دقيقة ',
      iconColor: 'blue',
    },
    {
      id: 4,
      title: 'التذاكر قبل الوقت ',
      icon: IconConstant.TICKET,
      info: '46',
      iconColor: 'orange',
    },
    {
      id: 5,
      title: 'التذاكر خلال الوقت ',
      icon: IconConstant.TICKET,
      info: '46',
      iconColor: 'green',
    },
    {
      id: 6,
      title: 'التذاكر بعد الوقت ',
      icon: IconConstant.TICKET,
      info: '46',
      iconColor: 'red',
    },
  ];

  static readonly TicketAttendanceCard: card[] = [
    {
      id: 1,
      title: '  إجمالي التذاكر  ',
      icon: IconConstant.TICKET,
      info: '630',
      iconColor: 'orange',
    },
    {
      id: 2,
      title: '  التذاكر المطبوعة   ',
      icon: IconConstant.TICKET,
      info: '530',
      iconColor: 'green',
    },
    {
      id: 3,
      title: '  التذاكر غير المطبوعة ',
      icon: IconConstant.TICKET,
      info: ' 13 دقيقة ',
      iconColor: 'blue',
    },
  ];
  static readonly dummyAppointmentPeriods: AppointmentBranchFlat[] = [
    {
      branchName: 'مدينة عيسى',
      day: 'الأحد',
      date1: '2025-09-25',
      date2: '2025-09-29',
      availableAppointments: 10,
      bookedAppointments: 9,
      totalAppointments: 19,
      periods: [
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '7:30 ص',
        },
        {
          availableAppointments2: 11,
          bookedAppointments2: 9,
          remainingAppointments: 2,
          periods: '8:00 ص',
        },
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '8:30 ص',
        },
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '9:00 ص',
        },
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '9:30 ص',
        },
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '10:00 ص',
        },
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '10:30 ص',
        },
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '11:00 ص',
        },
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '11:30 ص',
        },
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '12:00 م',
        },
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '12:30 م',
        },
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '1:00 م',
        },
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '1:30 م',
        },
        {
          availableAppointments2: 10,
          bookedAppointments2: 9,
          remainingAppointments: 1,
          periods: '2:00 م',
        },
        {
          availableAppointments2: 11,
          bookedAppointments2: 9,
          remainingAppointments: 2,
          periods: '2:30 م',
        },
      ],
    },
    {
      branchName: 'المحرق',
      day: 'الإثنين',
      date1: '2025-09-26',
      date2: '2025-09-30',
      availableAppointments: 8,
      bookedAppointments: 5,
      totalAppointments: 13,
      periods: [
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '7:30 ص',
        },
        {
          availableAppointments2: 9,
          bookedAppointments2: 6,
          remainingAppointments: 3,
          periods: '8:00 ص',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '8:30 ص',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '9:00 ص',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '9:30 ص',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '10:00 ص',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '10:30 ص',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '11:00 ص',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '11:30 ص',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '12:00 م',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '12:30 م',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '1:00 م',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '1:30 م',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '2:00 م',
        },
        {
          availableAppointments2: 8,
          bookedAppointments2: 5,
          remainingAppointments: 3,
          periods: '2:30 م',
        },
      ],
    },
    {
      branchName: 'ميناء سلمان',
      day: 'الثلاثاء',
      date1: '2025-08-21',
      date2: '2025-08-30',
      availableAppointments: 12,
      bookedAppointments: 10,
      totalAppointments: 22,
      periods: [
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '7:30 ص',
        },
        {
          availableAppointments2: 13,
          bookedAppointments2: 11,
          remainingAppointments: 2,
          periods: '8:00 ص',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '8:30 ص',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '9:00 ص',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '9:30 ص',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '10:00 ص',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '10:30 ص',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '11:00 ص',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '11:30 ص',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '12:00 م',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '12:30 م',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '1:00 م',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '1:30 م',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '2:00 م',
        },
        {
          availableAppointments2: 12,
          bookedAppointments2: 10,
          remainingAppointments: 2,
          periods: '2:30 م',
        },
      ],
    },
  ];

  static readonly appoitmentTableNormal = {
    labels: ['الرقم الشخصي', 'تاريخ الموعد', 'الوقت', 'مكان'],

    data: [
      {
        cpr: '123456789',
        appointmentDate: '2025-09-23',
        time: '10:00 AM',
        place: 'محرق',
      },
      {
        cpr: '987654321',
        appointmentDate: '2025-09-24',
        time: '02:30 PM',
        place: 'مدينة عيسى',
      },
      {
        cpr: '456789123',
        appointmentDate: '2025-09-25',
        time: '11:30 AM',
        place: 'ميناء سلمان',
      },
      {
        cpr: '789123456',
        appointmentDate: '2025-09-26',
        time: '09:00 AM',
        place: 'محرق',
      },
      {
        cpr: '321654987',
        appointmentDate: '2025-09-27',
        time: '01:15 PM',
        place: 'مدينة عيسى',
      },
      {
        cpr: '654987321',
        appointmentDate: '2025-09-28',
        time: '03:45 PM',
        place: 'ميناء سلمان',
      },
      {
        cpr: '147258369',
        appointmentDate: '2025-09-29',
        time: '08:00 AM',
        place: 'محرق',
      },
      {
        cpr: '963852741',
        appointmentDate: '2025-09-30',
        time: '12:30 PM',
        place: 'مدينة عيسى',
      },

      {
        cpr: '369147258',
        appointmentDate: '2025-10-25',
        time: '02:00 PM',
        place: 'محرق',
      },
      {
        cpr: '741852963',
        appointmentDate: '2025-10-03',
        time: '11:15 AM',
        place: 'مدينة عيسى',
      },
      {
        cpr: '852963741',
        appointmentDate: '2025-10-04',
        time: '04:30 PM',
        place: 'ميناء سلمان',
      },
    ],
  };

  static readonly appoitmentAgentTableNormal = {
    labels: [
      ' الرقم الشخصي للمخلص ',
      ' الرقم الشخصي للعملاء ',
      'تاريخ الموعد',
      'الوقت ',
      ' الموقع ',
    ],

    data: [
      {
        cpr: '123456789', // المخلص
        clientCprs: ['111222333', '222333444'], // العملاء
        appointmentDate: '2025-09-23',
        time: '10:00 AM',
        place: 'محرق',
      },
      {
        cpr: '987654321',
        clientCprs: ['555666777'],
        appointmentDate: '2025-09-24',
        time: '02:30 PM',
        place: 'مدينة عيسى',
      },
      {
        cpr: '456789123',
        clientCprs: ['888999000', '111000222', '333444555'],
        appointmentDate: '2025-09-25',
        time: '11:30 AM',
        place: 'ميناء سلمان',
      },
      {
        cpr: '789123456',
        clientCprs: ['444555666', '777888999'],
        appointmentDate: '2025-09-26',
        time: '09:00 AM',
        place: 'محرق',
      },
      {
        cpr: '321654987',
        clientCprs: ['123123123'],
        appointmentDate: '2025-09-27',
        time: '01:15 PM',
        place: 'مدينة عيسى',
      },
      {
        cpr: '654987321',
        clientCprs: ['555666777', '888999000'],
        appointmentDate: '2025-09-28',
        time: '03:45 PM',
        place: 'ميناء سلمان',
      },
      {
        cpr: '147258369',
        clientCprs: ['222333444', '333444555'],
        appointmentDate: '2025-09-29',
        time: '08:00 AM',
        place: 'محرق',
      },
      {
        cpr: '963852741',
        clientCprs: ['999000111'],
        appointmentDate: '2025-09-30',
        time: '12:30 PM',
        place: 'مدينة عيسى',
      },
      {
        cpr: '369147258',
        clientCprs: ['444555666', '555666777', '666777888'],
        appointmentDate: '2025-10-01',
        time: '02:00 PM',
        place: 'محرق',
      },
      {
        cpr: '741852963',
        clientCprs: ['111222333'],
        appointmentDate: '2025-10-02',
        time: '11:15 AM',
        place: 'مدينة عيسى',
      },
    ],
  };

  static readonly allData: StatisticsData[] = [
    {
      startDate: new Date('2025-09-01'),
      endDate: new Date('2025-09-25'),
      reports: [
        { metric: 'عدد المواعيد', isaTown: 130, muharraq: 95 },
        { metric: 'عدد المواعيد المحجوزة', isaTown: 50, muharraq: 35 },
        {
          metric: 'عدد المواعيد المتوفرة / غير المحجوزة',
          isaTown: 80,
          muharraq: 60,
        },
        { metric: 'عدد المواعيد المتبقية', isaTown: 45, muharraq: 30 },
        { metric: 'عدد المواعيد المغلقة', isaTown: 35, muharraq: 28 },
        { metric: 'عدد المواعيد التي تم تغييرها', isaTown: 5, muharraq: 2 },
        { metric: 'عدد المواعيد التي تم حضورها', isaTown: 45, muharraq: 38 },
        {
          metric: 'عدد المواعيد التي لم يتم حضورها',
          isaTown: 85,
          muharraq: 57,
        },
        {
          metric: 'عدد دقائق التأخير',
          isaTown: '30 دقيقة',
          muharraq: '20 دقيقة',
        },
        { metric: 'عدد التذاكر', isaTown: 90, muharraq: 70 },
        { metric: 'عدد التذاكر المطبوعة', isaTown: 50, muharraq: 40 },
        { metric: 'عدد التذاكر غير المطبوعة', isaTown: 40, muharraq: 30 },
        {
          metric: 'عدد التذاكر المطبوعة قبل الموعد المحدد',
          isaTown: 80,
          muharraq: 60,
        },
        {
          metric: 'عدد التذاكر المطبوعة خلال الموعد المحدد',
          isaTown: 50,
          muharraq: 35,
        },
        {
          metric: 'عدد التذاكر المطبوعة بعد الموعد المحدد',
          isaTown: 60,
          muharraq: 45,
        },
        {
          metric: 'متوسط دقائق التأخير',
          isaTown: '12 دقيقة',
          muharraq: '10 دقائق',
        },
        {
          metric: 'متوسط ساعة الذروة',
          isaTown: '11:45 AM',
          muharraq: '10:45 AM',
        },
        { metric: 'يوم الذروة', isaTown: 'الإثنين', muharraq: 'الأربعاء' },
      ],
    },
    {
      startDate: new Date('2025-10-01'),
      endDate: new Date('2025-10-25'),
      reports: [
        { metric: 'عدد المواعيد', isaTown: 110, muharraq: 80 },
        { metric: 'عدد المواعيد المحجوزة', isaTown: 50, muharraq: 35 },
        {
          metric: 'عدد المواعيد المتوفرة / غير المحجوزة',
          isaTown: 80,
          muharraq: 60,
        },
        { metric: 'عدد المواعيد المتبقية', isaTown: 45, muharraq: 30 },
        { metric: 'عدد المواعيد المغلقة', isaTown: 35, muharraq: 28 },
        { metric: 'عدد المواعيد التي تم تغييرها', isaTown: 5, muharraq: 2 },
        { metric: 'عدد المواعيد التي تم حضورها', isaTown: 45, muharraq: 38 },
        {
          metric: 'عدد المواعيد التي لم يتم حضورها',
          isaTown: 85,
          muharraq: 57,
        },
        {
          metric: 'عدد دقائق التأخير',
          isaTown: '30 دقيقة',
          muharraq: '20 دقيقة',
        },
        { metric: 'عدد التذاكر', isaTown: 90, muharraq: 70 },
        { metric: 'عدد التذاكر المطبوعة', isaTown: 50, muharraq: 40 },
        { metric: 'عدد التذاكر غير المطبوعة', isaTown: 40, muharraq: 30 },
        {
          metric: 'عدد التذاكر المطبوعة قبل الموعد المحدد',
          isaTown: 80,
          muharraq: 60,
        },
        {
          metric: 'عدد التذاكر المطبوعة خلال الموعد المحدد',
          isaTown: 50,
          muharraq: 35,
        },
        {
          metric: 'عدد التذاكر المطبوعة بعد الموعد المحدد',
          isaTown: 60,
          muharraq: 45,
        },
        {
          metric: 'متوسط دقائق التأخير',
          isaTown: '12 دقيقة',
          muharraq: '10 دقائق',
        },
        {
          metric: 'متوسط ساعة الذروة',
          isaTown: '11:45 AM',
          muharraq: '10:45 AM',
        },
        { metric: 'يوم الذروة', isaTown: 'الثلاثاء', muharraq: 'الأربعاء' },
      ],
    },
    {
      startDate: new Date('2025-11-01'),
      endDate: new Date('2025-11-25'),
      reports: [
        { metric: 'عدد المواعيد', isaTown: 50, muharraq: 40 },
        { metric: 'عدد المواعيد المحجوزة', isaTown: 90, muharraq: 66 },
        {
          metric: 'عدد المواعيد المتوفرة / غير المحجوزة',
          isaTown: 80,
          muharraq: 60,
        },
        { metric: 'عدد المواعيد المتبقية', isaTown: 45, muharraq: 30 },
        { metric: 'عدد المواعيد المغلقة', isaTown: 35, muharraq: 28 },
        { metric: 'عدد المواعيد التي تم تغييرها', isaTown: 5, muharraq: 2 },
        { metric: 'عدد المواعيد التي تم حضورها', isaTown: 45, muharraq: 38 },
        {
          metric: 'عدد المواعيد التي لم يتم حضورها',
          isaTown: 85,
          muharraq: 57,
        },
        {
          metric: 'عدد دقائق التأخير',
          isaTown: '30 دقيقة',
          muharraq: '20 دقيقة',
        },
        { metric: 'عدد التذاكر', isaTown: 90, muharraq: 70 },
        { metric: 'عدد التذاكر المطبوعة', isaTown: 50, muharraq: 40 },
        { metric: 'عدد التذاكر غير المطبوعة', isaTown: 40, muharraq: 30 },
        {
          metric: 'عدد التذاكر المطبوعة قبل الموعد المحدد',
          isaTown: 80,
          muharraq: 60,
        },
        {
          metric: 'عدد التذاكر المطبوعة خلال الموعد المحدد',
          isaTown: 50,
          muharraq: 35,
        },
        {
          metric: 'عدد التذاكر المطبوعة بعد الموعد المحدد',
          isaTown: 60,
          muharraq: 45,
        },
        {
          metric: 'متوسط دقائق التأخير',
          isaTown: '12 دقيقة',
          muharraq: '10 دقائق',
        },
        {
          metric: 'متوسط ساعة الذروة',
          isaTown: '11:45 AM',
          muharraq: '10:45 AM',
        },
        { metric: 'يوم الذروة', isaTown: 'الخميس', muharraq: 'الاحد' },
      ],
    },
  ];
  static readonly NOTIFICATIONINFO: card[] = [
    {
      id: 1,
      icon: IconConstant.mail,
      title: 'إجمالي البريد الالكتروني اليوم',
      info: '45',
    },
    {
      id: 2,
      icon: IconConstant.messageSquare,
      title: 'إجمالي الرسائل النصية اليوم',
      info: '24',
    },
    {
      id: 3,
      icon: IconConstant.messageOpen,
      title: 'الرسائل المقروئة',
      info: '40',
    },
    {
      id: 4,
      icon: IconConstant.messageClosed,
      title: 'الرسائل غير المقروئة',
      info: '4',
    },
  ];

  static readonly notifications: NotificationTable[] = [
    {
      icon: IconConstant.CALENDAR,
      notificationType: 'حجز موعد جديد',
      date: '2025-8-06',
      time: '2:00 PM',
      description: 'Booked a new appointment',
      date_count: '2 دقائق مضت',
      user: 'Mariam Ali',
      cpr: '020148763',
      priority: 'low' as const,
    },
    {
      icon: IconConstant.USERS,
      notificationType: 'تحديث بيانات المستخدم',
      date: '2025-9-10',
      time: '11:30 AM',
      description: 'updated their information',
      date_count: '5 دقائق مضت',
      user: 'Ahmed Salman',
      cpr: '891234567',
      priority: 'medium' as const,
    },
    {
      icon: IconConstant.CR,
      notificationType: 'إرسال مستند جديد',
      date: '2025-9-28',
      time: '4:45 PM',
      description: 'submitted a new document',
      date_count: '10 دقائق مضت',
      user: 'Fatima Yusuf',
      cpr: '931256784',
      priority: 'medium' as const,
    },
    {
      icon: IconConstant.USERS,
      notificationType: 'تأكيد هوية المستخدم',
      date: '2025-10-01',
      time: '9:00 AM',
      description: 'has identified his user identity successfully',
      date_count: 'قبل ساعة',
      user: 'Salman Habib',
      cpr: '850987654',
      priority: 'high' as const,
    },
    {
      icon: IconConstant.CALENDAR,
      notificationType: 'حجز موعد جديد',
      date: '2025-9-06',
      time: '2:00 PM',
      description: 'Booked a new appointment',
      date_count: '5 دقائق مضت',
      user: 'Sara Isa',
      cpr: '020148763',
      priority: 'low' as const,
    },
  ];

  static readonly calendarDatesOnly: CalendarDate[] = [
    {
      date: '2025-08-01',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-02',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-03',
      totalAppointment: 20,
      bookedAppointment: 15,
      unbookedAppointment: 5,
      startTime: '08:00',
      endTime: '16:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-04',
      totalAppointment: 22,
      bookedAppointment: 18,
      unbookedAppointment: 4,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-05',
      totalAppointment: 18,
      bookedAppointment: 12,
      unbookedAppointment: 6,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-06',
      totalAppointment: 28,
      bookedAppointment: 25,
      unbookedAppointment: 3,
      startTime: '07:00',
      endTime: '15:00',
      period: '15min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-07',
      totalAppointment: 24,
      bookedAppointment: 20,
      unbookedAppointment: 4,
      startTime: '10:00',
      endTime: '18:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-08',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-09',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-10',
      totalAppointment: 25,
      bookedAppointment: 18,
      unbookedAppointment: 7,
      startTime: '08:00',
      endTime: '16:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-11',
      totalAppointment: 20,
      bookedAppointment: 18,
      unbookedAppointment: 2,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-12',
      totalAppointment: 18,
      bookedAppointment: 10,
      unbookedAppointment: 8,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-13',
      totalAppointment: 30,
      bookedAppointment: 30,
      unbookedAppointment: 0,
      startTime: '07:00',
      endTime: '15:00',
      period: '15min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-14',
      totalAppointment: 22,
      bookedAppointment: 15,
      unbookedAppointment: 7,
      startTime: '10:00',
      endTime: '18:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-15',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-16',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-17',
      totalAppointment: 20,
      bookedAppointment: 15,
      unbookedAppointment: 5,
      startTime: '08:00',
      endTime: '16:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-18',
      totalAppointment: 25,
      bookedAppointment: 20,
      unbookedAppointment: 5,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-19',
      totalAppointment: 18,
      bookedAppointment: 10,
      unbookedAppointment: 8,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-20',
      totalAppointment: 30,
      bookedAppointment: 30,
      unbookedAppointment: 0,
      startTime: '07:00',
      endTime: '15:00',
      period: '15min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-21',
      totalAppointment: 22,
      bookedAppointment: 12,
      unbookedAppointment: 10,
      startTime: '10:00',
      endTime: '18:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-22',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-23',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-24',
      totalAppointment: 20,
      bookedAppointment: 15,
      unbookedAppointment: 5,
      startTime: '08:00',
      endTime: '16:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-25',
      totalAppointment: 25,
      bookedAppointment: 20,
      unbookedAppointment: 5,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-26',
      totalAppointment: 18,
      bookedAppointment: 10,
      unbookedAppointment: 8,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-27',
      totalAppointment: 30,
      bookedAppointment: 30,
      unbookedAppointment: 0,
      startTime: '07:00',
      endTime: '15:00',
      period: '15min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-28',
      totalAppointment: 22,
      bookedAppointment: 12,
      unbookedAppointment: 10,
      startTime: '10:00',
      endTime: '18:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-29',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-08-30',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },

    {
      date: '2025-08-31',
      totalAppointment: 20,
      bookedAppointment: 10,
      unbookedAppointment: 10,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-01',
      totalAppointment: 24,
      bookedAppointment: 20,
      unbookedAppointment: 4,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-02',
      totalAppointment: 18,
      bookedAppointment: 14,
      unbookedAppointment: 4,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-03',
      totalAppointment: 26,
      bookedAppointment: 21,
      unbookedAppointment: 5,
      startTime: '07:00',
      endTime: '15:00',
      period: '15min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-04',
      totalAppointment: 22,
      bookedAppointment: 17,
      unbookedAppointment: 5,
      startTime: '10:00',
      endTime: '18:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-05',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-06',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-07',
      totalAppointment: 20,
      bookedAppointment: 15,
      unbookedAppointment: 5,
      startTime: '08:00',
      endTime: '16:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-08',
      totalAppointment: 25,
      bookedAppointment: 20,
      unbookedAppointment: 5,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-09',
      totalAppointment: 18,
      bookedAppointment: 10,
      unbookedAppointment: 8,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-10',
      totalAppointment: 30,
      bookedAppointment: 30,
      unbookedAppointment: 0,
      startTime: '07:00',
      endTime: '15:00',
      period: '15min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-11',
      totalAppointment: 22,
      bookedAppointment: 12,
      unbookedAppointment: 10,
      startTime: '10:00',
      endTime: '18:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-12',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-13',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-14',
      totalAppointment: 24,
      bookedAppointment: 20,
      unbookedAppointment: 4,
      startTime: '08:00',
      endTime: '16:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-15',
      totalAppointment: 22,
      bookedAppointment: 16,
      unbookedAppointment: 6,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-16',
      totalAppointment: 20,
      bookedAppointment: 10,
      unbookedAppointment: 10,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-17',
      totalAppointment: 30,
      bookedAppointment: 25,
      unbookedAppointment: 5,
      startTime: '07:00',
      endTime: '15:00',
      period: '15min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-18',
      totalAppointment: 20,
      bookedAppointment: 10,
      unbookedAppointment: 10,
      startTime: '10:00',
      endTime: '18:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-19',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-20',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-21',
      totalAppointment: 24,
      bookedAppointment: 18,
      unbookedAppointment: 6,
      startTime: '08:00',
      endTime: '16:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-22',
      totalAppointment: 26,
      bookedAppointment: 22,
      unbookedAppointment: 4,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-23',
      totalAppointment: 19,
      bookedAppointment: 11,
      unbookedAppointment: 8,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-24',
      totalAppointment: 29,
      bookedAppointment: 29,
      unbookedAppointment: 0,
      startTime: '07:00',
      endTime: '15:00',
      period: '15min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-25',
      totalAppointment: 23,
      bookedAppointment: 14,
      unbookedAppointment: 9,
      startTime: '10:00',
      endTime: '18:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-26',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-27',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-28',
      totalAppointment: 20,
      bookedAppointment: 10,
      unbookedAppointment: 10,
      startTime: '08:00',
      endTime: '16:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-29',
      totalAppointment: 25,
      bookedAppointment: 20,
      unbookedAppointment: 5,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-30',
      totalAppointment: 18,
      bookedAppointment: 10,
      unbookedAppointment: 8,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'مدينة عيسى',
    },
    {
      date: '2025-09-01',
      totalAppointment: 24,
      bookedAppointment: 20,
      unbookedAppointment: 4,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-02',
      totalAppointment: 18,
      bookedAppointment: 14,
      unbookedAppointment: 4,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-03',
      totalAppointment: 26,
      bookedAppointment: 21,
      unbookedAppointment: 5,
      startTime: '07:00',
      endTime: '15:00',
      period: '15min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-04',
      totalAppointment: 22,
      bookedAppointment: 17,
      unbookedAppointment: 5,
      startTime: '10:00',
      endTime: '18:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-05',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'المحرق',
    },
    {
      date: '2025-09-06',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'المحرق',
    },
    {
      date: '2025-09-07',
      totalAppointment: 20,
      bookedAppointment: 15,
      unbookedAppointment: 5,
      startTime: '08:00',
      endTime: '16:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-08',
      totalAppointment: 25,
      bookedAppointment: 20,
      unbookedAppointment: 5,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-09',
      totalAppointment: 18,
      bookedAppointment: 10,
      unbookedAppointment: 8,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-10',
      totalAppointment: 30,
      bookedAppointment: 30,
      unbookedAppointment: 0,
      startTime: '07:00',
      endTime: '15:00',
      period: '15min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-11',
      totalAppointment: 22,
      bookedAppointment: 12,
      unbookedAppointment: 10,
      startTime: '10:00',
      endTime: '18:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-12',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'المحرق',
    },
    {
      date: '2025-09-13',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'المحرق',
    },
    {
      date: '2025-09-14',
      totalAppointment: 24,
      bookedAppointment: 20,
      unbookedAppointment: 4,
      startTime: '08:00',
      endTime: '16:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-15',
      totalAppointment: 22,
      bookedAppointment: 16,
      unbookedAppointment: 6,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-16',
      totalAppointment: 20,
      bookedAppointment: 10,
      unbookedAppointment: 10,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-17',
      totalAppointment: 30,
      bookedAppointment: 25,
      unbookedAppointment: 5,
      startTime: '07:00',
      endTime: '15:00',
      period: '15min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-18',
      totalAppointment: 20,
      bookedAppointment: 10,
      unbookedAppointment: 10,
      startTime: '10:00',
      endTime: '18:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-19',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'المحرق',
    },
    {
      date: '2025-09-20',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'المحرق',
    },
    {
      date: '2025-09-21',
      totalAppointment: 24,
      bookedAppointment: 18,
      unbookedAppointment: 6,
      startTime: '08:00',
      endTime: '16:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-22',
      totalAppointment: 26,
      bookedAppointment: 22,
      unbookedAppointment: 4,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-23',
      totalAppointment: 19,
      bookedAppointment: 11,
      unbookedAppointment: 8,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-24',
      totalAppointment: 29,
      bookedAppointment: 29,
      unbookedAppointment: 0,
      startTime: '07:00',
      endTime: '15:00',
      period: '15min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-25',
      totalAppointment: 23,
      bookedAppointment: 14,
      unbookedAppointment: 9,
      startTime: '10:00',
      endTime: '18:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-26',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'المحرق',
    },
    {
      date: '2025-09-27',
      totalAppointment: 0,
      bookedAppointment: 0,
      unbookedAppointment: 0,
      startTime: '00:00',
      endTime: '00:00',
      period: '-',
      branch: 'المحرق',
    },
    {
      date: '2025-09-28',
      totalAppointment: 20,
      bookedAppointment: 10,
      unbookedAppointment: 10,
      startTime: '08:00',
      endTime: '16:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-29',
      totalAppointment: 25,
      bookedAppointment: 20,
      unbookedAppointment: 5,
      startTime: '09:00',
      endTime: '17:00',
      period: '30min',
      branch: 'المحرق',
    },
    {
      date: '2025-09-30',
      totalAppointment: 18,
      bookedAppointment: 10,
      unbookedAppointment: 8,
      startTime: '08:30',
      endTime: '15:30',
      period: '20min',
      branch: 'المحرق',
    },
  ];
}
